### ISSUE TITLE
Rename "nwfsc-assess" organization to reflect use by both NWFSC and SWFSC?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/PEPtools#16]
Renaming a github organization is easy and most links are automatically redirected as discussed here:
https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization

The "nwfsc-assess" organization contains tools used by both NWFSC and SWFSC staff and folks from both centers are "owners" of the organization. In theory folks outside of these science centers who are working with west coast stocks or their data may want to use these tools too. Therefore, how about renaming the organization to something like "westcoast-assess" to better reflect that shared use?

@melissamonk-NOAA and @EJDick-NOAA, if this would feel like trying to assimilate you into the borg, and you would prefer to have a separate SWFSC github organization or just use your own github accounts to host shared things, we can support that path instead.

Questions, comments, concerns?

EDIT: Checklist added 24 October 2022:
- [x] agree on new "pfmc-assessments" name
- [x] make change on github
- [x] change all instances of "nwfsc-assess" to "pfmc-assessments" in each package (currently ~58~ [32 as of 18-Nov-22] instances occur: https://github.com/search?q=org%3Apfmc-assessments+nwfsc-assess&type=code)
- [x] all users should update their local git clones to point to new remote URL (see info in comments near bottom of this issue): 
  - https://github.com/pfmc-assessments/PEPtools/issues/16#issuecomment-1262881077
  - https://github.com/pfmc-assessments/PEPtools/issues/16#issuecomment-1264538368

**Comment by EJDick-NOAA** [comment]
I like the idea of having a single site for both centers. Our two groups focus on groundfish, but we could also invite the SWFSC CPS and HMS assessors to the party. That would expand our SS3 community, and bring some new ideas and perspectives on how we do things.

**Comment by melissamonk-NOAA** [comment]
@iantaylor-NOAA we had just been floating the idea of making a swfsc-assess group, but this makes more sense than two different groups.

**Comment by kellijohnson-NOAA** [comment]
Please list other options for name choices by commenting on this issue. One option per comment. Use thumbs up emoji to vote for your choice. Voting will end September 21st.

Then, I think we should open a new organization and keep nwfsc-assess. That way we can keep repositories that we do not want to move over here. Any repositories that should be renamed, e.g., PacFIN.Utilities because the name is long and contains a full stop, which is not accepted for R naming of packages, can be renamed and moved at the same time.

**Comment by kellijohnson-NOAA** [comment]
pacific-assess

**Comment by kellijohnson-NOAA** [comment]
pfmc-assess

**Comment by andi-stephens-NOAA** [comment]
West-Coast-groundfish-assess

**Comment by melissamonk-NOAA** [comment]
pfmc-assessment-tools

**Comment by iantaylor-NOAA** [comment]
Good plan @kellijohnson-NOAA. 
Revisions I would suggest are 1. voting for not just a single favorite but all those you like, and 2. planning to retire nwfsc-assess eventually and keeping it up as an interim solution (for however long).

I voted for my two favorites (which I like because they are specific to our council, whereas I now realize "west coast", which I previously proposed, and "pacific" are very broad).

**Comment by EJDick-NOAA** [comment]
I agree, @iantaylor-NOAA, and suggest that we avoid the abbreviation "assess"

**Comment by kellijohnson-NOAA** [comment]
@EJDick-NOAA @chantelwetzel-noaa and I have had lengthy discussions previously about optimal naming strategies and the reason that "assess" continues to be prevalent is to continue to match "pbs-assess" which potentially was based off of "nwfsc-assess". I am not exactly sure which organization came first. I agree that abbreviations are not ideal but typing long names is also not ideal. Though, I would rather have a long organization name than a long repository or branch name. So, perhaps a middle ground can be found with "pfmc-assessment"?

**Comment by EJDick-NOAA** [comment]
I like the middle-ground suggestion by @kellijohnson-NOAA, but am also content with assess if the other assessors are so inclined.

**Comment by kellijohnson-NOAA** [comment]
So what do we want to come after "pfmc-"? 
- pfmc-assessment-tools
- pfmc-assessment
- pfmc-assess

I would like to decide by Wednesday so we can move forward.

**Comment by iantaylor-NOAA** [comment]
After discussion with @kellijohnson-NOAA and @melissamonk-NOAA this morning, we think there are two leading contenders based on the votes and comments above and our further discussion: 1. `pfmc-assessments` (which is consistent with the AFSC github organization: https://github.com/afsc-assessments), and 2. `pfmc-assess` (which is consistent with our current name and the Pacific Biological Station organization: https://github.com/pbs-assess).

Please vote one more time via thumbs up on only one of the following two comments for those options. Vote will close 24 hours from these comments (10:30am Pacific time).

**Comment by iantaylor-NOAA** [comment]
pfmc-assessments

**Comment by iantaylor-NOAA** [comment]
pfmc-assess

**Comment by owenhamel** [comment]
wfsc-assess

**Comment by iantaylor-NOAA** [comment]
**New name**
After 24 hours of voting, **"pfmc-assessments"** is the winning new organization name by a small margin. If the comment above to "avoid the abbreviation 'assess'" is assumed to count as a vote, the margin is larger.

**How to make it happen**
I like the idea of a cleaned-up set of repositories that we would get by creating a new organization and moving only the repositories that we want to maintain as proposed by @kellijohnson-NOAA above: https://github.com/nwfsc-assess/PEPtools/issues/16#issuecomment-1239738173. 

The table below contains my initial guess on which of the 18 repositories seems clearly worth moving and which are less obvious to me. Please edit this comment to fill in the table as you see fit. Seems like the only question marks are for the geostatistical stuff, so we could also consult with more folks involved with those past efforts who (e.g. Thorson, Ward, and Shelton). The links and references should be automatically updated whether we follow the guide to transferring repositories (https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) or the guide to renaming organizations (https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization). I think we can create a cleaned up set of repos either way.

**What to move**
  | repository | move? | notes
-- | -- | -- | --
1 | .github | yes | just contains the README.md for the organization
2 | assessment_archive | delete | redundant with https://github.com/chantelwetzel-noaa/assessment_prioritization
3 | Assessment_Background_Materials | yes 
4 | canary_2023 | yes 
5 | geostatistical_delta-GLMM | ? | current URL is referenced in Thorson et al. 2015: https://doi.org/10.1093/icesjms/fsu243 but will theoretically forward automatically
6 | lingcod | yes 
7 | nwfscAgeingError | yes 
8 | nwfscDeltaGLM | ? | current URL is referenced in Thorson et al. 2015: https://doi.org/10.1093/icesjms/fsu243 but will theoretically forward automatically
9 | nwfscDiag | yes 
10 | nwfscDiscard | yes 
11 | nwfscMapping | ? | last code contribution was in 2018 by @chantelwetzel-noaa but a functional mapping package would be useful
12 | nwfscSurvey | yes 
13 | PacFIN.Utilities | yes | also rename to avoid "." in name
14 | PEPtools | yes 
15 | rebuilder | yes | 
16 | RecFIN | yes | work in progress, may need to be split in two https://github.com/nwfsc-assess/RecFIN/issues/6
17 | sa4ss | yes
18 | VASTWestCoast | ? | do we need this in the future since the move to sdmTMB has been endorsed by the SSC?

**Comment by okenk** [comment]
What if we did the rename, but archived the repositories that are no longer in use?

https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

**Comment by iantaylor-NOAA** [comment]
@James-Thorson-NOAA, @OleShelton, and @ericward-noaa, heads up that we're planning on renaming to "nwfsc-assess" organization to "pfmc-assessments" and are hoping to do some repository cleanup at the same time (see my comment above: https://github.com/nwfsc-assess/PEPtools/issues/16#issuecomment-1254256608). 

Your 2013 paper "Geostatistical delta-generalized linear mixed models improve precision for estimated abundance indices for West Coast groundfishes" includes the URLS https://github.com/nwfsc-assess/geostatistical_delta-GLMM and https://github.com/nwfsc-assess/nwfscDeltaGLM. 

Do you have any concerns if we rename the nwfsc-assess organization, which will cause those URLs to change, but the published URLs will continue to forward to the new address? The alternative would be to move all the other repos to a new pfmc-assessments org, but keeping the nwfsc-assess org just to continue to host those two repositories.

Also, are these repositories being actively maintained (I see lots of 2021 commits by Eric to nwfscDeltaGLM but less on the other), or should we consider archiving them (info on archiving repos in link in comment immediately before this one).

**Comment by James-Thorson-NOAA** [comment]
I'm fine changing the base-URL, given that the existing URL will then forward appropriately.

**Comment by ericward-noaa** [comment]
Same -- I've followed most of the conversation, and seems reasonable. 

Re: the nwfscDeltaGLM commits, I think I was just doing some cleaning and testing, but to my knowledge that isn't used for anything. It would be useful to put on the list of packages to archive?

**Comment by iantaylor-NOAA** [comment]
Thanks for the quick feedback @James-Thorson-NOAA and @ericward-noaa. Archiving nwfscDeltaGLM would make it clear to folks that it's no longer being actively maintained, but it would still be accessible as read-only. It could be un-archived at some point in the future if someone needed to do something with it. What about geostatistical_delta-GLMM?

**Comment by James-Thorson-NOAA** [comment]
I think my next version of VAST fully deprecates the dependency.  could we wait to discuss again next year?

**Comment by iantaylor-NOAA** [comment]
Yes, no rush at all. I forgot there was a dependency. Feel free to check in at any point in the future if/when you think it should be archived.

**Comment by James-Thorson-NOAA** [comment]
Yeah, previously I've maintained the previous model-estimate results from when I was using spatialDeltaGLMM in that package.  I then loaded it, ran integrated tests in VAST, and confirmed that it was fully backwards compatible w.r.t. previous results.  However, I'm in the process of moving those records over to FishStatsUtils.

Jim

**Comment by iantaylor-NOAA** [comment]
Our organization is now renamed to "pfmc-assessments".

We had reached consensus on renaming the organization. I thought about proposing a specific time to make the change to allow folks to prepare, but I don't think there's anything to prepare, so I went ahead and made the change a few minutes ago.

The [GitHub guide to renaming organizations](https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization) says 
> You can continue pushing your local repositories to the old remote tracking URL without updating it. However, we recommend you update all existing remote repository URLs after changing your organization name. Because your old organization name is available for use by anyone else after you change it, the new organization owner can create repositories that override the redirect entries to your repository. For more information, see "Managing remote repositories."

I just pushed a commit to {nwfscAgeingError} without updating my local repo and it worked fine. 
Then I updated my remote via the following commands:

Get current URL for the remote that my computer is looking at
```
> git remote get-url origin
https://github.com/nwfsc-assess/nwfscAgeingError.git
```
Update to new URL
```
>git remote set-url origin https://github.com/pfmc-assessments/nwfscAgeingError.git
```
Then I pushed another change and it worked fine again.

If someone wants to post a suggestion for a reliable way to update all the remote URLs for all 18-ish repositories in this organization, please do so. I think the only element of this being time sensitive is that if we don't remember to do it now, we will forget that it should be done someday.

**Comment by kellijohnson-NOAA** [comment]
There might be a better way but I used a little bit of bash code. This works because I have all repos for an organization stored in a directory. So, if you navigate a bash shell to the directory that stores all of the repos for pfmc-assessments, you can run
```
for f in ` ls | awk '{print substr($1, 1, length($1)-1)}'`;
  do
    cd $f
    git remote set-url origin https://github.com/pfmc-assessments/$f.git
    cd ..
  done
```
I checked that it worked with
```
for f in ` ls `
  do cd $f
    git remote get-url origin
    cd ..
  done
```

As an additional note, you can clone  all of the repos from pfmc-assessments using
```
curl "https://api.github.com/orgs/pfmc-assessments/repos?page=1&per_page=100" |
  grep -e 'clone_url*' |
  cut -d \" -f 4 |
  xargs -L1 git clone
```

**Comment by iantaylor-NOAA** [comment]
As noted in https://github.com/pfmc-assessments/nwfscSurvey/issues/82, we need to update all the instances of "nwfsc-assess" in the READMEs and other elements in the package in this repository. 

There are currently 58 instances of "nwfsc-assess" in the code throughout the organization: https://github.com/search?q=org%3Apfmc-assessments+nwfsc-assess&type=code.

I would suggest that the lead author/maintainer listed in the DESCRIPTION for each package be responsible for making this change, rather than having a dialogue about who will do the work and/or creating an issue in each repo.

**Comment by James-Thorson-NOAA** [comment]
I just released VAST 3.10.0.  This removes all remaining dependencies on repo "pfmc-assessments/geostatistical_delta-GLMM", and all archived runs used in integrated-testing for backwards compatibility have been moved to `FishStatsUtils`.

Do y'all still wanna deprecate it somehow, as mentioned earlier in the thread?

**Comment by iantaylor-NOAA** [comment]
Thanks for following up on this @James-Thorson-NOAA.
It's easy to "archive" the repository which makes it read-only and puts a yellow banner across the top as can be seen at https://github.com/pfmc-assessments/nwfscDeltaGLM.
Is there anything you would want to add or subtract from the README first to point folks to other places? We can always un-archive it in the future to make changes, but better to just do it now.

**Comment by James-Thorson-NOAA** [comment]
OK, I pulled the Applications wiki tab into VAST, and removed it from this repo.  I also made a pull request editing the README, although I gather someone has to review and accept the PR given that I'm not longer in the organization.  

Once that's done, I think we're ready to freeze it with the Deprecated banner as you note.

**Comment by iantaylor-NOAA** [comment]
Thanks @James-Thorson-NOAA. 
Your README changes have been merged and the https://github.com/pfmc-assessments/geostatistical_delta-GLMM repo is now archived.

**Comment by James-Thorson-NOAA** [comment]
Awesome!  That's something of a milestone.  thanks for your help!

**Comment by kellijohnson-NOAA** [comment]
I unarchived, edited, and re-archived some repositories to fix references to the previous name. As of 2023-06-14 the following three repositories are the only repositories left that need changes. After you update your repository, can you please check the box.

- [ ] canary
- [ ] copper
- [ ] petrale
