### ISSUE TITLE
Create functions to check data and control file

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/PEPtools#21]
@iantaylor-NOAA and @brianlangseth-NOAA will find the google doc that lists things that should be checked. Then this list could be turned into a function to check the files for things that should be set rather than creating template files.

**Comment by brianlangseth-NOAA** [comment]
Google doc with some ideas for starter, forecast, and rebuilder is linked [here](https://docs.google.com/document/d/1_bw81a0iF-BeP11kuPenqMGIZb1tYrh8JRqlvpK6rw8/edit). Need to start for .dat and .ctl files.
