### ISSUE TITLE
problems with SPAM in pfmc-assessments discussions

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/PEPtools#23]
I got three email notifications this afternoon for messages in our github discussions today that were spam. 
In one case I blocked the account and deleted the message. In the other two cases the messages had been deleted by the time I saw the email notification, perhaps by one of you or perhaps as a result of some spam filter that github uses.

I don't see an way to restrict who has access to the discussions for a public repository, but maybe one of you know of something. Better yet, github may improve their spam filtering so we don't have to worry about it again.

**Comment by okenk** [comment]
I blocked and hid a couple and also reported to github. I heard from someone at AFSC their discussion boards were also getting spammed this afternoon, so I think the issue might be site-wide.

**Comment by iantaylor-NOAA** [comment]
No further SPAM since that group of occurrences last week, so closing this issue. Thanks @okenk for hiding & reporting.
