### ISSUE TITLE
stop using "ghost fleet"?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [pfmc-assessments/PEPtools#26]
Discussion at data and stock assessment open forum today highlighted the inconsistent and sometimes obsolete use of the term "ghost fleet".

My memory is that early versions of Stock Synthesis (around the time I got to NWFSC in 2008), you couldn't have multiple observations for the same fleet/year so you had to create a separate "ghost fleet" with no likelihood weight to estimate the implied fit to the marginal comps if you used conditional age-at-length data. Current SS3 makes this easier so now we are typically just using "ghost data" associated with the same fleet because you can remove the duplication observations from the likelihood. 

@chantelwetzel-noaa noted that for Copper Rockfish, they have created a fleet with no catch in order to see the implied fit to some data that were collected in a way that differs from the rest. This seems much closer to the original definition of "ghost fleet", but also can be misleading.

We don't want the use of "ghost fleet" in any of these contexts to imply IUU fishing.

How about for the Copper Rockfish application we use a term like "no-catch fleet"? 

Looking at {r4ss} just now, I see that "ghost fleet" is only used in some of the documentation. However, the `SSplotData()` figure labels include "Ghost age compositions" and "Ghost length compositions" and the comp plot captions includes the text `'Ghost' observations (not included in the likelihood)... `. Those uses seem to have less room for confusion but if somebody has a better idea, it would be easy to change the figure labels and captions. Would "Implied age compositions" or "Implied observations" be better?

**Comment by brianlangseth-NOAA** [comment]
I would prefer we avoid using the term implied. Begs the question of what the implication is from. 

Im ok with use of the term "ghost" for compositions not included in the likelihood (and for what its worth I have no problem with the term ghost fleet). If ghost is being interpretted as IUU, we could alternatively remove that term and have only 'observations not included in the likelihood' for captions.

**Comment by kellijohnson-NOAA** [comment]
I like being more implicit and just stating "Observations not included in the likelihood" instead of ghost to be **EXTREMELY** clear.

**Comment by chantelwetzel-noaa** [comment]
I think that eliminating the term "ghost fleet" from our vocabulary entirely would be a good approach. Let's just say what we mean, and mean what we say.  :)

**Comment by shcaba** [comment]
I agree with Chantel and [The Fixx](https://youtu.be/JHYIGy1dyd8) that clearly stating what we are doing is best for future proofing our communication.

**Comment by iantaylor-NOAA** [comment]
Here are some r4ss changes that change "Ghost..." to "Excluded..." in all the visible places: https://github.com/r4ss/r4ss/commit/82028d40e69d18250dae91b61514dcca695ef19c. I think changing variable names would be more likely to break stuff for folks. "Excluded" isn't as clear as "not included in the likelihood", but fits better in a legend or figure title.

**Comment by iantaylor-NOAA** [comment]
The consensus of this discussion was to stop using "ghost fleet" and the r4ss branch changing "Ghost..." to "Excluded..." in figure captions has been merged. Some form of "ghost" is still used in r4ss variable names, but I think that's not a big deal and would be too disruptive to change.
